name: INT001 Deploy

on:
  push:
    branches:
      - main
    paths:
      - INT001-calendar-to-todoist/**
  workflow_dispatch:

env:
  INT001_PATH: INT001-calendar-to-todoist
  FUNCTIONAPP_NAME: func-pd-int001-calendar-to-todoist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore ${{ env.INT001_PATH }}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${{ env.INT001_PATH }}
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal ${{ env.INT001_PATH }}
    - name: Publish
      run: dotnet publish ${{ env.INT001_PATH }}/src/Function/Function.csproj --configuration Release --output functionapp
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: functionapp
        path: functionapp/**
        if-no-files-found: error
    - name: Upload an ARM Template Artifact
      uses: actions/upload-artifact@v3
      with:
        name: infra
        path: ${{ env.INT001_PATH }}/infra/**
        if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: 'INT001 Production'
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: functionapp
        path: functionapp
    - name: Download an ARM Template Artifact
      uses: actions/download-artifact@v3
      with:
        name: infra
        path: infra
    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: infra/main.bicep
        parameters: infra/parameters.json
        failOnStdErr: false
    - name: Deploy Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.FUNCTIONAPP_NAME }}
        package: functionapp
        publish-profile: ${{ secrets.INT001_AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
    - name: Logout via Azure CLI
      run: az logout
