name: INT001 CI

on:
  push:
    branches-ignore:
      - main
    paths:
      - INT001-calendar-to-todoist/**
  pull_request:
    branches:
      - main
    paths:
      - INT001-calendar-to-todoist/**
  workflow_dispatch:

env:
  INT001_PATH: INT001-calendar-to-todoist

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore ${{ env.INT001_PATH }}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${{ env.INT001_PATH }}
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal ${{ env.INT001_PATH }}
